version: 2
updates:
    -
        package-ecosystem: composer
        directory: "/"
        schedule:
            interval: monthly
        versioning-strategy: lockfile-only
        allow:
            - dependency-type: development
        ignore:
            -
                dependency-name: "*"
                update-types: ["version-update:semver-major"] # never update major versions
        groups:
            dev-dependencies:
                dependency-type: development
